name: monitor repos
on:
  schedule:
    # Run every day
    - cron: '0 1 * * *'
jobs:
  monitor_repos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - repo: stereolabs/zed-ros2-wrapper
          path: zed_wrapper/launch/zed_camera.launch.py
    steps:
      - uses: actions/checkout@v2
      - uses: poll-github-repo/action@v1
        with:
          repo-to-sync: ${{ matrix.repo }}
          path-to-sync: ${{ matrix.path }}
          cache-path: .sync/${{ matrix.repo }}/${{ matrix.path }}
          tracking-issue-label: upstream-sensor-updates-md
  
          # Template for tracking issue title (see available placeholders below)
          tracking-issue-title: "Update on {{ path }}: {{ sha-short }}"
  
          # Template for tracking issue body (see available placeholders below)
          tracking-issue-body: |
              New commit in ${{ matrix.repo }}:
  
              **{{ message }}** [link]({{ url }})
          token: ${{ secrets.GITHUB_TOKEN }}
          yes-create-issues: false
